import { Box, Container } from "@mui/material";
import type { Metadata } from "next";
import localFont from "next/font/local";
import MainNavigation from "./components/MainNavigation";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container maxWidth="md" sx={{ padding: 0 }}>
          <Box sx={{ pb: 7 }}>
            {children}
            <MainNavigation></MainNavigation>
          </Box>
        </Container>
      </body>
    </html>
  );
}
